Autodesk/pgbelt

pyproject.toml
The `^~4.1.1 ` has `~` and `^`, that's a syntax error. CI is failing to build due to it.
=> ci: syntax error for flake8 version number

.github/workflows/constraints.txt
Reverts Autodesk/pgbelt#217
Apparently broke the release action. https://github.com/Autodesk/pgbelt/actions/runs/4864843131
=> fix:  undo bump of virtualenv, back to 20.21.0

pgbelt/cmd/convenience.py, tests/integration/test_integration.py
This command will try to open a socket connection to either one DB (source and dest) or all DBs in a datacenter.
It will collect all the results and display them in a table, Green for connect OK and False for a failure.
It will also exit 1 if ANY failure was found, otherwise exit 0.
```
❯ belt check-connectivity somedc
dbup.all.somedc.config:INFO Getting all available configurations...
dbup.somedb.somedc.config:INFO Getting configuration...
..
dbup.somedb99999.somedc.connect.dst:ERROR Cannot access network port. timed out.
database                   src connect ok    dst connect ok
-------------------------  ----------------  ----------------
somedb1                    False             True
somedb2                    False             True
...
somedb99                   False …
```
=> feat: check-connectivity command

Makefile, pyproject.toml
The previous `make install` command would not produce the `belt` CLI tool for local testing. This PR fixes that, so you are able to make local changes and actually run `belt` to test them.
=> test: ability to build and install pgbelt CLI locally for testing

Makefile, docker-compose.yml, pyproject.toml, tests/integration/conftest.py
With this new code, we can simply run `make local-dev` to get the following:
1. Two Postgres DBs get spun up as Docker containers, one loaded with test data,
2. One container as a shell running a local version of `belt`
This way, if you need to test new features or commands, you can quickly test them against databases.
This builds and leaves around some docker containers. To clean up, run `make clean-docker`.
=> test: muuuuch easier local development

pgbelt/config/remote.py
This helps us know from the remote config plugin what error the plugin itself saw when it throw an error.
=> fix: remote.py error handling needs to shore up plugin error

pgbelt/cmd/setup.py, pgbelt/util/pglogical.py
Fixes #278, so users don't run into permission issues running migrations after a pgbelt migration is complete.
=> fix: grant pglogical schema usage #278

pgbelt/util/pglogical.py
Fixes #271 
Confirmed by running a whole cutover with our local dev environment `make local-dev`, then ran `belt teardown` at the end, then truncated the tables in the destination, then started replication again. Confirmed the `users` table was populated in the end!
=> fix: stop using default replication set

docs/usage.md, pgbelt/cmd/sync.py
Do not load NOT VALID constraints or create INDEXes for exodus-style migrations.
Fixes #309
=> feat: handle exodus-style migrations

.gitignore, CONTRIBUTING.md, Dockerfile, docker-compose.yml
@jdcallet brought this up as a good feature to have.
This change allows for usage of `make local-dev` to not require you to clean up your local environment to alter your code and build a new testable copy of `belt`.
You can now instead run `make local-dev` to spin up the SRC/DST DB containers, and your `belt` container instead builds `belt` based on the local code you have on your laptop as a volume. Therefore, when you make a code change, you can just run `pip install -e .` to update your test container's `belt` binary instead of rebuilding everything.
Note: it is indeed redundant to volume while the container is built with the build-time copy of the `pgbelt` code. I decided against removing that local copy in the Dockerfile to keep our CI steps from not needing to install `poetry` …
=> test: local dev container uses local mount for faster testing

CHANGELOG.md, pgbelt/cmd/convenience.py, pgbelt/cmd/preflight.py, pgbelt/cmd/status.py, pgbelt/util/postgres.py
https://github.com/Autodesk/pgbelt/issues/296
This add 3 new columns to the status command: src_db_size. dst_db_size, and progress. Those columns show values when the status is _initializing_, if not they show as n/a.
=> feat: add percent progress to initializing status view

.gitignore, Dockerfile, local_dev_scripts/README.md, local_dev_scripts/generate_large_test_data.py, pgbelt/cmd/status.py, pgbelt/util/pglogical.py, pgbelt/util/postgres.py, tests/integration/files/test_schema_data.sql
Addresses #392 
This PR also does the following:
- Local-dev had a problem with poetry venv locations - fixed that in the Dockerfile
- Added a script to generate large datasets for easier testing of the `initializing` phase
- Added an extra PK table in the integration test for exodus-style testing
=> fix: sizes in status to should target config dataset instead of whole DB

.gitignore, Makefile, tests/integration/conftest.py, tests/integration/test_integration.py
This includes a big refactor on the integration test, to make it modular for multiplexing the workflow against various test cases.
This PR is missing the following, which may be just filed as separate issues:
- Parallelization of the integration tests - this needs some thought (especially on how to collect all the output in a legible way)
- Finishing up the Exodus tests - they won't pass in the current state because we do a total dump comparison between the source and destination. Exodus implies that only a subset of data gets migrated, so the test needs to support that.
=> test: update integration tests to check non-public schemas

pgbelt/cmd/setup.py, pgbelt/cmd/status.py, pgbelt/cmd/sync.py, pgbelt/util/postgres.py, tests/integration/conftest.py, tests/integration/files/test_schema_data.sql
=> fix: support for table names with capitals

pgbelt/cmd/setup.py, pgbelt/cmd/status.py, pgbelt/cmd/sync.py, pgbelt/util/pglogical.py, pgbelt/util/postgres.py, tests/integration/files/test_schema_data.sql
Integration tests didn't actually have capitals inside the DBs, so our testing passed but didn't fix the issue for customers.
Integration tests are now fixed, and our code was fixed accordingly too. Fixes #420
=> fix: actual table capitalization support

pgbelt/config/models.py, pgbelt/config/remote.py, tests/integration/conftest.py, tests/integration/test_integration.py
Only the following is left:
```
../venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:272
../venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:272
/opt/venv/lib/python3.11/site-packages/pydantic/_internal/_config.py:272: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.6/migration/
warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
```
=> refactor: all but one deprecation warning eliminated

pgbelt/cmd/login.py, tests/integration/test_integration.py
=> fix: revoke-logins skips owner if owner is same as root #509

docs/quickstart.md, pgbelt/cmd/teardown.py
Quickstart updated with instructions on `teardown` and `teardown --full`.
Code comments for `--full` are updated too, it only drops the extension and the role drop was moved into the default behaviour before.
=> docs: update quickstart and code comments to explain how to teardown properly

pgbelt/util/postgres.py, tests/integration/files/test_schema_data.sql
Problem:
Capitals in Sequence Names would yield errors like `relation "non_public_schema.users_id_seq" does not exist` for a sequence named `userS_id_seq`. Previously we thought the integration test covered this but the schema SQL didn't wrap the sequence names in quotes.
Solved it in this PR! Integration test works!
=> fix: support for capital letters in sequence names

pgbelt/util/logs.py
Fixes #557
In ipython:
import pgbelt.util.logs
logger = logs.get_logger("dba", "dcb")
logger.info('d message')
2024-09-17 11:26:53 dbup.dba.dcb:INFO d message
DBAAS-92
=> fix: add timestamps to logs DBAAS-92

.github/workflows/release-please.yml
Updating due to https://github.com/Autodesk/pgbelt/actions/runs/11276987149/job/31362090071
```
Warning: google-github-actions/release-please-action is deprecated, please use googleapis/release-please-action instead.
```
=> ci: move to new release-please gha repo

pgbelt/util/dump.py
Couldn't run `remove-indexes` without it showing a syntax error from PSQL. This fixes it.
=> fix: remove-indexes syntax error fix

tests/integration/files/postgres13-pglogical-docker/Dockerfile
https://github.com/2ndQuadrant/pglogical
README shows that the pglogical package now is hosted by the Postgres repo instead of 2ndQuadrant now.
=> ci: pglogical source has changed
